name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa | head -n 5
        echo "HOST: ${{ secrets.EC2_HOST }}"   

    - name: Copy index.html to EC2
      run: |
        scp index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

    - name: Move file and restart web server
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo mv /tmp/index.html /var/www/html/index.html
          sudo systemctl restart httpd || sudo systemctl restart apache2
        EOF
